name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo ${{ github.event.ref }}

      - name: Action
        run: echo ${{ github.event.action }}

      - name: Pull request is draft
        run: echo ${{ github.event.pull_request.draft }}

      - name: Pull request is draft
        run: echo ${{ github.event.pull_request.draft }}

      - name: Pull request state
        run: echo ${{ github.event.pull_request.state }}

  only_pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.opened == true }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Only on a PR
