name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo $${{ github.event  }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!!

  only_pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.opened == true }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Only on a PR
